pipeline:
  build:
    image: golang:1.6
    commands:
      - go get github.com/stretchr/testify/assert
      - go get github.com/axw/gocov/gocov
      - go get github.com/mattn/goveralls
      - go build github.com/mattn/goveralls
      - go test ./... -cover
      - packages=$(find . -type d -maxdepth 1 -not -iname .git -exec echo -package {} \;)
      - goveralls -service drone.io -repotoken $COVERALLS_TOKEN $packages
